package container

import (
	"strings"
	"testing"
	"time"

	"github.com/Hyzokaaa/opencroft/internal/database/domain/entities"
	"github.com/Hyzokaaa/opencroft/internal/database/domain/enums"
	"github.com/Hyzokaaa/opencroft/internal/shared/plan"
)

func postgres() *entities.Database {
	return entities.NewDatabase(entities.DatabaseProps{
		Name: "main", Engine: enums.EnginePostgres, DB: "appdb", User: "app",
	})
}

func planner() *Planner { return NewPlanner("lxc", "helpdesk") }

func provision(d *entities.Database, services ...string) plan.Plan {
	return planner().Provision(d, time.Unix(0, 0), []string{d.Name}, services)
}

func text(p plan.Plan) string {
	lines := []string{}
	for _, step := range p.Steps {
		lines = append(lines, step.Shell())
	}
	return strings.Join(lines, "\n")
}

// Installing an engine writes to disk, and here the disk is the whole point.
func TestTheSnapshotIsTakenBeforeAnythingElse(t *testing.T) {
	steps := provision(postgres()).Steps

	if len(steps) == 0 {
		t.Fatal("empty plan")
	}
	if !strings.Contains(steps[0].Shell(), "snapshot") {
		t.Fatalf("the first step is %q", steps[0].Shell())
	}
}

// Nothing in this module runs a shell on the host.
//
// The one host-level `sh -c` croft has is the readiness check in the deploy
// planner, and it is where an unquoted field once reached root. Provisioning
// has no reason to need one: everything happens inside the container. This
// test fails the day that stops being true.
func TestNothingRunsAShellOnTheHost(t *testing.T) {
	plans := []plan.Plan{
		provision(postgres(), "backend"),
		planner().Destroy(postgres(), time.Unix(0, 0), nil, nil, []string{"backend"}),
	}

	for _, p := range plans {
		for _, step := range p.Steps {
			if len(step.Argv) == 0 {
				t.Fatalf("%q has no command", step.Describe)
			}
			if step.Argv[0] != "lxc" {
				t.Errorf("%q runs %q on the host", step.Describe, step.Argv[0])
			}
		}
	}
}

// The password is generated by the step that uses it, so the plan a person
// reads carries no secret — there is nothing to leak into the panel, the
// browser or a job event.
func TestThePlanCarriesNoSecret(t *testing.T) {
	body := text(provision(postgres()))

	if !strings.Contains(body, "/dev/urandom") {
		t.Error("the password is not generated inside the container")
	}

	// Every place a credential appears, it is the shell variable and not a
	// value. A literal would mean it existed before the plan was read.
	for _, line := range strings.Split(body, "\n") {
		if !strings.Contains(line, "PASSWORD") && !strings.Contains(line, "PGPASSWORD") {
			continue
		}
		if !strings.Contains(line, "$PW") {
			t.Errorf("a credential is spelled out: %q", line)
		}
	}
}

// A database beside its application talks over the loopback, which the
// container already guards. Editing pg_hba.conf to achieve nothing would be a
// file we touched for no reason, and one more thing to detect drift on.
func TestALocalDatabaseTouchesNoConfiguration(t *testing.T) {
	body := text(provision(postgres()))

	for _, path := range []string{"pg_hba.conf", "postgresql.conf", "listen_addresses"} {
		if strings.Contains(body, path) {
			t.Errorf("a local database touches %s", path)
		}
	}
}

// Provisioning must never rewrite a unit. The unit reads a fixed path, written
// once when the service was deployed; that is what keeps the two modules from
// having to know about each other.
func TestNoUnitIsRewritten(t *testing.T) {
	body := text(provision(postgres(), "backend", "worker"))

	if strings.Contains(body, "/etc/systemd/system") {
		t.Error("provisioning rewrites a unit file")
	}
	if !strings.Contains(body, "systemctl restart croft-backend") {
		t.Error("the service is never restarted, so it will not see the credentials")
	}
}

// The credentials go in their own file, and the file the person edits is a
// different one — a deployment rewrites that one on every run.
func TestTheCredentialsAreNotInTheFileADeploymentRewrites(t *testing.T) {
	body := text(provision(postgres()))

	if !strings.Contains(body, entities.Dir+"/main.env") {
		t.Error("the credentials are not written to the database's own file")
	}
	if strings.Contains(body, "/srv/") {
		t.Error("the credentials were written beside the code, where a deployment will overwrite them")
	}
}

// Redis on the loopback inside one container is guarded by the container. A
// password nobody will ever rotate is not a second lock.
func TestRedisIsProvisionedWithoutCredentials(t *testing.T) {
	cache := entities.NewDatabase(entities.DatabaseProps{
		Name: "cache", Engine: enums.EngineRedis,
	})
	body := text(provision(cache))

	if strings.Contains(body, "$PW") {
		t.Error("redis was given a password")
	}
	if !strings.Contains(body, "REDIS_URL=redis://127.0.0.1:6379/0") {
		t.Error("nothing tells the application where redis is")
	}
}

// Dropping a database is the one irreversible thing here, so the snapshot
// before it carries a kind that pruning never reaches.
func TestDroppingLeavesAWayBackForever(t *testing.T) {
	steps := planner().Destroy(postgres(), time.Unix(0, 0), nil, nil, nil).Steps

	first := steps[0].Shell()
	if !strings.Contains(first, entities.FarewellKind) {
		t.Fatalf("the first step is %q", first)
	}
	if strings.Contains(first, "croft-deploy-") {
		t.Fatal("the farewell snapshot is prunable")
	}
}

// A failure halfway should leave a database the panel still knows about,
// rather than data nobody remembers owning.
func TestWhatCroftRecordedIsForgottenLast(t *testing.T) {
	steps := planner().Destroy(postgres(), time.Unix(0, 0),
		[]string{"user.croft.database.main.engine"}, nil, nil).Steps

	dropped, forgot := -1, -1
	for i, step := range steps {
		if strings.Contains(step.Shell(), "DROP DATABASE") {
			dropped = i
		}
		if strings.Contains(step.Shell(), "config unset") {
			forgot = i
		}
	}

	if dropped < 0 || forgot < 0 {
		t.Fatalf("the plan is missing a step:\n%s", text(planner().Destroy(
			postgres(), time.Unix(0, 0), []string{"user.croft.database.main.engine"}, nil, nil)))
	}
	if forgot < dropped {
		t.Error("the annotations are forgotten before the data is dropped")
	}
}

// The index never disagrees with what is actually on the container.
func TestTheIndexIsLeftSayingWhatRemains(t *testing.T) {
	body := text(planner().Destroy(postgres(), time.Unix(0, 0), nil, []string{"cache"}, nil))

	if !strings.Contains(body, "config set helpdesk "+entities.IndexKey+" cache") {
		t.Errorf("the index is not left saying what remains:\n%s", body)
	}
}
